title: Centural
email: "NOT FUNCTIONAL AT THE MOMENT: admin@centural.co"
description: ""
baseurl: ""
url: "http://centural.co"
twitter_username: CenturalPortal
github_username:  Centural

analytics:
  provider: google
  google:
    tracking_id: UA-108131263-1

comments:
  provider: disqus
  disqus:
    shortname: centuralportal

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

#Systemantically Awesome Style Sheets
sass:
  load_paths:
    - assets/_scss
    - node_modules
  style: :compressed

# Custom site configuration
lang: en

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

include:
- _stylesheets
- _javascript

defaults:
  -
    scope:
      path: ""
    values:
      lang: "en"